version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: notes_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-notes_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Для запуска миграций (опционально)
  migrate:
    image: migrate/migrate
    container_name: notes_migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./internal/database/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/${DB_NAME:-notes_db}?sslmode=disable",
      "up"
    ]
    profiles:
      - tools

volumes:
  postgres_data:
    name: notes_postgres_data