version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    container_name: lesson13-server
    ports:
      - "8080:8080"
    working_dir: /app
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: ./cmd/client/Dockerfile
    container_name: lesson13-client
    depends_on:
      - server
    working_dir: /app
    stdin_open: true
    tty: true
    restart: "no"
    profiles:
      - client